# Generated by Django 5.0.3 on 2024-03-11 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contactee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_as_contactee', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_as_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
